// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R6Ranking.Data;

#nullable disable

namespace R6Ranking.Migrations
{
    [DbContext(typeof(R6EsportsDbContext))]
    [Migration("20240822044244_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R6Ranking.Models.Match", b =>
                {
                    b.Property<int>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchID"));

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Team1ID")
                        .HasColumnType("int");

                    b.Property<int>("Team1Score")
                        .HasColumnType("int");

                    b.Property<int>("Team2ID")
                        .HasColumnType("int");

                    b.Property<int>("Team2Score")
                        .HasColumnType("int");

                    b.Property<int>("TournamentID")
                        .HasColumnType("int");

                    b.HasKey("MatchID");

                    b.HasIndex("Team1ID");

                    b.HasIndex("Team2ID");

                    b.HasIndex("TournamentID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("R6Ranking.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("R6Ranking.Models.PlayerEloHistory", b =>
                {
                    b.Property<int>("EloHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EloHistoryID"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EloChange")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("MatchID")
                        .HasColumnType("int");

                    b.Property<decimal>("NewElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("OldElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("EloHistoryID");

                    b.HasIndex("MatchID");

                    b.HasIndex("PlayerID");

                    b.ToTable("PlayerEloHistories");
                });

            modelBuilder.Entity("R6Ranking.Models.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RegionID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("R6Ranking.Models.RegionEloHistory", b =>
                {
                    b.Property<int>("RegionEloHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionEloHistoryID"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EloChange")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("NewElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("OldElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("RegionEloHistoryID");

                    b.HasIndex("RegionID");

                    b.ToTable("RegionEloHistories");
                });

            modelBuilder.Entity("R6Ranking.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<string>("Coach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("RegionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TeamID");

                    b.HasIndex("RegionID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("R6Ranking.Models.TeamEloChange", b =>
                {
                    b.Property<int>("TeamEloChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamEloChangeID"));

                    b.Property<decimal>("CurrentElo")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EloChange")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int?>("MatchID")
                        .HasColumnType("int");

                    b.Property<int?>("RivalTeamID")
                        .HasColumnType("int");

                    b.Property<string>("RivalTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.Property<string>("TournamentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamEloChangeID");

                    b.HasIndex("MatchID");

                    b.HasIndex("RivalTeamID");

                    b.HasIndex("TeamID");

                    b.ToTable("TeamEloChanges");
                });

            modelBuilder.Entity("R6Ranking.Models.TeamLogo", b =>
                {
                    b.Property<int>("TeamLogoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamLogoID"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("TeamLogoID");

                    b.HasIndex("TeamID")
                        .IsUnique();

                    b.ToTable("TeamsLogo");
                });

            modelBuilder.Entity("R6Ranking.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentID"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamID")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerTeamID")
                        .HasColumnType("int");

                    b.HasKey("TournamentID");

                    b.HasIndex("RegionID");

                    b.HasIndex("TeamID");

                    b.HasIndex("WinnerTeamID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("R6Ranking.Models.Match", b =>
                {
                    b.HasOne("R6Ranking.Models.Team", "Team1")
                        .WithMany("MatchesAsTeam1")
                        .HasForeignKey("Team1ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("R6Ranking.Models.Team", "Team2")
                        .WithMany("MatchesAsTeam2")
                        .HasForeignKey("Team2ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("R6Ranking.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team1");

                    b.Navigation("Team2");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("R6Ranking.Models.Player", b =>
                {
                    b.HasOne("R6Ranking.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("R6Ranking.Models.PlayerEloHistory", b =>
                {
                    b.HasOne("R6Ranking.Models.Match", "Match")
                        .WithMany("PlayerEloHistories")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R6Ranking.Models.Player", "Player")
                        .WithMany("PlayerEloHistories")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("R6Ranking.Models.RegionEloHistory", b =>
                {
                    b.HasOne("R6Ranking.Models.Region", "Region")
                        .WithMany("RegionEloHistories")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("R6Ranking.Models.Team", b =>
                {
                    b.HasOne("R6Ranking.Models.Region", "Region")
                        .WithMany("Teams")
                        .HasForeignKey("RegionID");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("R6Ranking.Models.TeamEloChange", b =>
                {
                    b.HasOne("R6Ranking.Models.Match", "Match")
                        .WithMany("TeamEloChanges")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("R6Ranking.Models.Team", "RivalTeam")
                        .WithMany()
                        .HasForeignKey("RivalTeamID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("R6Ranking.Models.Team", "Team")
                        .WithMany("TeamEloChanges")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("RivalTeam");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("R6Ranking.Models.TeamLogo", b =>
                {
                    b.HasOne("R6Ranking.Models.Team", "Team")
                        .WithOne("Logo")
                        .HasForeignKey("R6Ranking.Models.TeamLogo", "TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("R6Ranking.Models.Tournament", b =>
                {
                    b.HasOne("R6Ranking.Models.Region", "Region")
                        .WithMany("Tournaments")
                        .HasForeignKey("RegionID");

                    b.HasOne("R6Ranking.Models.Team", null)
                        .WithMany("WonTournaments")
                        .HasForeignKey("TeamID");

                    b.HasOne("R6Ranking.Models.Team", "WinnerTeam")
                        .WithMany()
                        .HasForeignKey("WinnerTeamID");

                    b.Navigation("Region");

                    b.Navigation("WinnerTeam");
                });

            modelBuilder.Entity("R6Ranking.Models.Match", b =>
                {
                    b.Navigation("PlayerEloHistories");

                    b.Navigation("TeamEloChanges");
                });

            modelBuilder.Entity("R6Ranking.Models.Player", b =>
                {
                    b.Navigation("PlayerEloHistories");
                });

            modelBuilder.Entity("R6Ranking.Models.Region", b =>
                {
                    b.Navigation("RegionEloHistories");

                    b.Navigation("Teams");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("R6Ranking.Models.Team", b =>
                {
                    b.Navigation("Logo");

                    b.Navigation("MatchesAsTeam1");

                    b.Navigation("MatchesAsTeam2");

                    b.Navigation("Players");

                    b.Navigation("TeamEloChanges");

                    b.Navigation("WonTournaments");
                });

            modelBuilder.Entity("R6Ranking.Models.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
